#version: "3.9"
networks:
  nginx-network:
    external: true

services:
  portifoliov1:
    image: nginx:latest
    ports:
      - 85:80

    volumes:
      - ./dist:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - nginx-network
