#version: "3.9"
networks:
  nginx-network:
    external: true

services:
  portifolio:
    image: nginx:latest

    volumes:
      - ./dist:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - nginx-network
